### ISSUE TITLE
JSON Schema Form Version Mismatch

### ISSUE THREAD

**Issue by dfreeman06** [deathbeds/wxyz#47]
Looks like the WXYZ JSON Schema Form Version is still indicated 0.4.0 on the 0.4.1 release. 

https://github.com/deathbeds/wxyz/blob/v0.4.1/src/ts/wxyz-json-schema-form/src/index.ts#L2

**Comment by bollwyvl** [comment]
Excellent catch.

On #46, I'm working on moving more of that information to a single source of truth (specifically the `package.json`) for python and typescript, and intend to get at least _an_ 0.4.x release out, while being ready to do different packaging for lab 3 (#42).
