### ISSUE TITLE
Collapsable table widget?

### ISSUE THREAD

**Issue by NicolasRouquette** [deathbeds/wxyz#67]
Assuming that it is possible to get a UI that looks like the example here:

https://dgothrek.gitlab.io/ipyaggrid/guide/customize.html#user-params

Specifically:  

![image](https://user-images.githubusercontent.com/2359166/159087931-6145f73f-64ea-4d44-8677-e5fb4cb97b2f.png)

How would we define a Python panda table/dict to do the same kind of thing with `wxyz_datagrid`?

A related question: is there a way to add some event callbacks?

E.g, if the user clicks on a row/col table cell, can we get a callback event in Python? 

The use case would be display in some kind of property sheet UI some information pertaining to the table selection.

**Comment by bollwyvl** [comment]
[Merged cells](https://github.com/jupyterlab/lumino/pull/124) have been supported upstream for a while, but I haven't had the opportunity to enable working with it in a sensible way. I was hoping to get there with #61, but there is rather a lot to do.

> event callbacks

`SelectGrid` (and by extension `StyleGrid`) offer [`.selections`](https://github.com/deathbeds/wxyz/blob/master/src/wxyz_datagrid/src/wxyz/datagrid/widget_selectgrid.py#L34), and is demonstrated in [an example](https://github.com/deathbeds/wxyz/blob/master/src/wxyz_notebooks/src/wxyz/notebooks/Examples/SelectGrid.ipynb).

**Comment by NicolasRouquette** [comment]
Hum... thanks for the prompt feedback and the links to the code.
Is it correct to conclude that a collapsable/expandable table widget is not yet available in `wxyz`?

**Comment by bollwyvl** [comment]
>  a collapsable/expandable table widget is not yet available

yep
